HELLO_LIST = [
    "hello",
    "hi",
    "hey",
    "howdy",
    "greetings",
    "salutations",
    "aloha",
    "hiya",
    "what's up",
    "yo",
    "how's it going",
    "good morning",
    "good afternoon",
    "good evening",
    "hi there",
    "how are you",
    "what's going on",
    "hey there",
    "sup",
    "salve",
    "ciao",
    "bonjour",
    "hola",
    "hallo",
    "namaste",
    "konnichiwa",
    "ni hao",
    "peace",
    "how's everything",
    "long time no see",
    "how's life",
    "what's new",
    "welcome",
    "yo yo",
    "how you doing",
    "what's up bro",
    "how's your day",
    "good to see you",
    "hiya there",
    "what's crackin",
    "yo dude",
    "good to meet you",
    "what's happening",
    "how's the family",
    "all good",
    "glad to see you",
    "cheerio",
    "hey buddy",
    "hiya mate",
    "привіт",
    "доброго дня",
    "добрий ранок",
    "добрий вечір",
    "здрастуйте",
]

INFO_LIST = [
    "info",
    "information",
    "опис",
    "data",
    "facts",
    "details",
    "news",
    "report",
    "message",
    "update",
    "content",
    "article",
    "story",
    "announcement",
    "notification",
    "alert",
    "discussion",
    "query",
    "response",
    "document",
    "file",
    "record",
    "overview",
    "description",
    "summary",
    "guide",
    "tip",
    "question",
    "answer",
    "insight",
    "source",
    "headline",
    "факт",
    "повідомлення",
    "дані",
    "деталі",
    "результати",
]
GAME_LIST = [
    "game",
    "play",
    "move",
    "win",
    "lose",
    "start",
    "end",
    "turn",
    "goal",
    "action",
    "level",
    "score",
    "team",
    "playable",
    "turn",
    "challenge",
    "гра",
    "грати",
    "почати",
]
PLAYING_GIF = "https://s5.ezgif.com/tmp/ezgif-51b8a9ea76d91d.webp"
